"""Protocol interfaces that both simulator and real hardware must implement."""

from pathlib import Path, PurePosixPath
from typing import Any, Protocol, runtime_checkable

from openblade.domain.models import (
    CartridgeState,
    DriveStatus,
    FileInstance,
    LibraryInventory,
    LTFSFileStat,
    MountHandle,
    MountMode,
    OperationResult,
    SlotState,
)
from openblade.domain.policies import FormatConfirmation


@runtime_checkable
class LibraryBackend(Protocol):
    def inventory(self) -> LibraryInventory: ...
    def load(self, source_slot: int, drive_id: int) -> OperationResult: ...
    def unload(self, drive_id: int, target_slot: int) -> OperationResult: ...
    def move(self, source_slot: int, target_slot: int) -> OperationResult: ...
    def get_drive(self, drive_id: int) -> DriveStatus: ...
    def get_slot(self, slot_id: int) -> SlotState: ...
    def find_slot_by_barcode(self, barcode: str) -> int | None: ...
    def find_drive_by_barcode(self, barcode: str) -> int | None: ...
    def get_all_barcodes(self) -> list[str]: ...
    def get_cartridge_state(self, barcode: str) -> CartridgeState | None: ...


@runtime_checkable
class LTFSBackend(Protocol):
    def format(self, barcode: str, confirmation: FormatConfirmation) -> OperationResult: ...
    def mount(self, barcode: str, mode: MountMode) -> MountHandle: ...
    def unmount(self, handle: MountHandle) -> OperationResult: ...
    def write_file(
        self, handle: MountHandle, source: Path, dest: PurePosixPath
    ) -> FileInstance: ...
    def read_file(
        self, handle: MountHandle, source: PurePosixPath, dest: Path
    ) -> OperationResult: ...
    def stat(self, handle: MountHandle, path: PurePosixPath) -> LTFSFileStat: ...
    def ensure_tape(self, barcode: str) -> Any: ...  # backend-specific tape-contents object
    def remaining_capacity(self, barcode: str) -> int: ...
    def read_bytes(
        self, barcode_or_path: str, path: PurePosixPath | str | None = None
    ) -> bytes | None: ...
