"""Registry of public operational error codes."""

from __future__ import annotations

from openblade.nas.types import ErrorCodeEntry

KNOWN_ERROR_CODES: list[ErrorCodeEntry] = [
    ErrorCodeEntry(
        code="SAFETY_001",
        severity="error",
        title="Tape operation without orchestrator",
        description="A tape hardware call was made outside TapeOperationOrchestrator.",
        action="Route all tape operations through TapeOperationOrchestrator.execute().",
    ),
    ErrorCodeEntry(
        code="SAFETY_002",
        severity="error",
        title="Format without confirmation",
        description="A tape format was attempted without confirmed_format=True.",
        action="Set extras={'confirmed_format': True} in TapeOpRequest.",
    ),
    ErrorCodeEntry(
        code="SAFETY_003",
        severity="error",
        title="Forbidden import pattern",
        description="Direct hardware access detected in a non-orchestrator module.",
        action="Use TapeOperationOrchestrator for all tape operations.",
    ),
    ErrorCodeEntry(
        code="AUTH_001",
        severity="error",
        title="Authentication required",
        description="Request requires authentication.",
        action="Log in via POST /aml/users/login and include session cookie.",
    ),
    ErrorCodeEntry(
        code="AUTH_002",
        severity="error",
        title="Insufficient permissions",
        description="Authenticated user lacks required RBAC permission.",
        action="Request a role with the required permission from an admin.",
    ),
    ErrorCodeEntry(
        code="GATEWAY_001",
        severity="error",
        title="Gateway backend unavailable",
        description="The SFTP gateway could not start because its runtime dependency is unavailable.",
        action="Install asyncssh in the API environment and retry starting the gateway.",
    ),
    ErrorCodeEntry(
        code="GATEWAY_002",
        severity="error",
        title="Gateway bind failure",
        description="The SFTP gateway could not bind to the configured host or port.",
        action="Verify the configured host and port are free, then restart the gateway.",
    ),
    ErrorCodeEntry(
        code="GATEWAY_003",
        severity="warning",
        title="Gateway session limit reached",
        description="The gateway rejected a new session because the maximum concurrent session count was reached.",
        action="Wait for an existing session to disconnect or raise the configured session limit.",
    ),
    ErrorCodeEntry(
        code="CATALOG_001",
        severity="warning",
        title="Manifest missing",
        description="Tape content exists but the expected manifest metadata could not be found.",
        action="Run catalog rebuild to regenerate metadata or re-archive the affected content.",
    ),
    ErrorCodeEntry(
        code="CATALOG_002",
        severity="error",
        title="Manifest corrupt",
        description="Catalog metadata exists but could not be parsed or validated.",
        action="Restore from a known-good manifest version or rebuild the catalog shard.",
    ),
    ErrorCodeEntry(
        code="CATALOG_003",
        severity="warning",
        title="Dataset missing files",
        description="The catalog dataset references one or more files which no longer have a valid tape instance.",
        action="Inspect catalog file instances and re-run archive for any missing paths.",
    ),
    ErrorCodeEntry(
        code="CATALOG_004",
        severity="error",
        title="Catalog rebuild failed",
        description="A catalog rebuild job did not complete successfully.",
        action="Review rebuild warnings, correct media issues, and re-run the rebuild job.",
    ),
    ErrorCodeEntry(
        code="NAS_001",
        severity="error",
        title="NAS policy missing",
        description="A requested NAS storage policy does not exist.",
        action="Create the storage policy or update the share or pool to use a valid policy id.",
    ),
    ErrorCodeEntry(
        code="NAS_002",
        severity="warning",
        title="NAS policy still referenced",
        description="A NAS storage policy cannot be removed because it is still attached to a share or virtual pool.",
        action="Reassign the dependent shares or pools, then retry the delete operation.",
    ),
    ErrorCodeEntry(
        code="NAS_003",
        severity="error",
        title="NAS pool configuration invalid",
        description="A NAS virtual pool could not be saved because its configuration failed validation.",
        action="Review mount path, policy, cache target, and access mode values before retrying.",
    ),
    ErrorCodeEntry(
        code="RESTORE_001",
        severity="warning",
        title="Restore queue missing tape",
        description="A restore request references tape media that is not currently available.",
        action="Load the missing barcode into the active library and rerun restore planning.",
    ),
    ErrorCodeEntry(
        code="RESTORE_002",
        severity="error",
        title="Restore plan failed",
        description="The restore planner could not build a safe execution plan for the requested files.",
        action="Review unavailable files, queue warnings, and pool configuration before retrying.",
    ),
    ErrorCodeEntry(
        code="SYS_001",
        severity="error",
        title="Database unreachable",
        description="The catalog database could not be reached.",
        action="Check db_url configuration and database file permissions.",
    ),
    ErrorCodeEntry(
        code="SYSTEM_001",
        severity="error",
        title="Database unreachable",
        description="The catalog database could not be reached.",
        action="Check db_url configuration and database file permissions.",
    ),
    ErrorCodeEntry(
        code="SYSTEM_002",
        severity="warning",
        title="System configuration incomplete",
        description="One or more expected OpenBlade configuration values are missing or still set to defaults.",
        action="Review the system configuration summary and update environment overrides as needed.",
    ),
]
