server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /library-1/ {
    proxy_pass ${EMULATOR_UI_TARGET_LIBRARY1_URL}/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /library-1;
  }

  location /library-2/ {
    proxy_pass ${EMULATOR_UI_TARGET_LIBRARY2_URL}/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /library-2;
  }

  location /library-3/ {
    proxy_pass ${EMULATOR_UI_TARGET_LIBRARY3_URL}/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /library-3;
  }
}
